# Generated by Django 5.0.3 on 2026-04-29 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Tax Number')),
                ('default_language', models.CharField(default='en', max_length=10, verbose_name='Default Language')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name='Opening Hours')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('subscription_plan', models.CharField(default='free', max_length=50, verbose_name='Subscription Plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_dine_in_orders', models.BooleanField(default=True, verbose_name='Allow Dine-in Orders')),
                ('allow_takeaway_orders', models.BooleanField(default=True, verbose_name='Allow Takeaway Orders')),
                ('allow_pre_orders', models.BooleanField(default=False, verbose_name='Allow Pre-orders')),
                ('allow_ai_recommendations', models.BooleanField(default=True, verbose_name='Allow AI Recommendations')),
                ('allow_loyalty', models.BooleanField(default=False, verbose_name='Allow Loyalty Program')),
                ('allow_reviews', models.BooleanField(default=True, verbose_name='Allow Reviews')),
                ('service_charge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Service Charge Percent')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax Percent')),
                ('average_preparation_time', models.IntegerField(default=15, verbose_name='Average Preparation Time (mins)')),
                ('theme_color', models.CharField(default='#000000', max_length=7, verbose_name='Theme Color')),
                ('show_calories', models.BooleanField(default=False, verbose_name='Show Calories')),
                ('show_allergens', models.BooleanField(default=True, verbose_name='Show Allergens')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
