# Generated by Django 5.2.13 on 2026-05-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_paypal',
            field=models.BooleanField(default=False, verbose_name='Enable PayPal'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_stripe',
            field=models.BooleanField(default=False, verbose_name='Enable Stripe'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_whatsapp_ordering',
            field=models.BooleanField(default=False, verbose_name='Enable WhatsApp Ordering'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='PayPal Client ID'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Public Key'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Secret Key'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Include country code, e.g. +90555...', max_length=20, verbose_name='WhatsApp Number'),
        ),
    ]
