# Generated by Django 6.0.6 on 2026-07-19 02:15

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RESTAURANT_OWNER', 'Restaurant Owner'), ('MANAGER', 'Manager'), ('WAITER', 'Waiter'), ('KITCHEN_STAFF', 'Kitchen Staff'), ('CASHIER', 'Cashier'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20, verbose_name='Role')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_upload_path, verbose_name='Avatar')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('can_view_daily_revenue', models.BooleanField(default=False, verbose_name='Can View Daily Revenue')),
                ('can_view_monthly_revenue', models.BooleanField(default=False, verbose_name='Can View Monthly Revenue')),
                ('can_view_yearly_revenue', models.BooleanField(default=False, verbose_name='Can View Yearly Revenue')),
                ('can_view_net_profit', models.BooleanField(default=False, verbose_name='Can View Net Profit')),
                ('can_view_expenses', models.BooleanField(default=False, verbose_name='Can View Expenses')),
                ('can_view_payroll', models.BooleanField(default=False, verbose_name='Can View Payroll')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='Can View Analytics')),
                ('can_view_kitchen_screen', models.BooleanField(default=False, verbose_name='Can View Kitchen Screen')),
                ('can_view_waiter_panel', models.BooleanField(default=False, verbose_name='Can View Waiter Panel')),
                ('can_view_cashier_panel', models.BooleanField(default=False, verbose_name='Can View Cashier Panel')),
                ('can_manage_menu', models.BooleanField(default=False, verbose_name='Can Manage Menu')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='Can Manage Inventory')),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='Can Manage Customers')),
                ('can_view_ai_reports', models.BooleanField(default=False, verbose_name='Can View AI Reports')),
                ('can_manage_campaigns', models.BooleanField(default=False, verbose_name='Can Manage Campaigns')),
                ('can_view_reviews', models.BooleanField(default=False, verbose_name='Can View Reviews')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Can Manage Settings')),
                ('can_manage_branches', models.BooleanField(default=False, verbose_name='Can Manage Branches')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('can_view_daily_revenue', models.BooleanField(default=False)),
                ('can_view_monthly_revenue', models.BooleanField(default=False)),
                ('can_view_yearly_revenue', models.BooleanField(default=False)),
                ('can_view_net_profit', models.BooleanField(default=False)),
                ('can_view_expenses', models.BooleanField(default=False)),
                ('can_view_payroll', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_view_kitchen_screen', models.BooleanField(default=False)),
                ('can_view_waiter_panel', models.BooleanField(default=False)),
                ('can_view_cashier_panel', models.BooleanField(default=False)),
                ('can_manage_menu', models.BooleanField(default=False)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_manage_customers', models.BooleanField(default=False)),
                ('can_view_ai_reports', models.BooleanField(default=False)),
                ('can_manage_campaigns', models.BooleanField(default=False)),
                ('can_view_reviews', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_manage_branches', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Role',
                'verbose_name_plural': 'Custom Roles',
            },
        ),
    ]
