# Generated by Django 6.0.6 on 2026-07-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription End Date'),
        ),
    ]
