# Generated by Django 6.0.6 on 2026-07-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_cashier',
            field=models.BooleanField(default=True, verbose_name='Enable Cashier Panel'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_courier',
            field=models.BooleanField(default=False, verbose_name='Enable Courier/Delivery'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_kds',
            field=models.BooleanField(default=True, verbose_name='Enable Kitchen Display System'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_menu_management',
            field=models.BooleanField(default=True, verbose_name='Enable Menu Management'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_reservations',
            field=models.BooleanField(default=True, verbose_name='Enable Reservations'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_waiter',
            field=models.BooleanField(default=True, verbose_name='Enable Waiter Panel'),
        ),
    ]
