# Generated by Django 6.0.6 on 2026-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantsettings_enable_cashier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_ai',
            field=models.BooleanField(default=True, verbose_name='Enable AI Features'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_finance',
            field=models.BooleanField(default=True, verbose_name='Enable Finance & Accounting'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_hr',
            field=models.BooleanField(default=True, verbose_name='Enable HR & Payroll'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_inventory',
            field=models.BooleanField(default=True, verbose_name='Enable Inventory'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_marketing',
            field=models.BooleanField(default=True, verbose_name='Enable Marketing'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_reports',
            field=models.BooleanField(default=True, verbose_name='Enable Reports'),
        ),
    ]
