# Generated by Django 6.0.6 on 2026-07-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantsettings_enable_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_tax_feature',
            field=models.BooleanField(default=True, verbose_name='Enable Tax/VAT Feature'),
        ),
    ]
