# Generated by Django 6.0.6 on 2026-07-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantsettings_enable_tax_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_branches',
            field=models.BooleanField(default=False, verbose_name='Enable Branch Management'),
        ),
    ]
