# Generated by Django 6.0.6 on 2026-07-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantsettings_enable_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='e.g. menu.myrestaurant.com or haket.neymanmenu.com', max_length=255, null=True, unique=True, verbose_name='Custom Domain'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_ai_assistant',
            field=models.BooleanField(default=True, verbose_name='Enable AI Assistant'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_ai_reports',
            field=models.BooleanField(default=True, verbose_name='Enable AI Reports'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_finance_expenses',
            field=models.BooleanField(default=True, verbose_name='Enable Expenses'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_finance_refunds',
            field=models.BooleanField(default=True, verbose_name='Enable Refunds'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_finance_z_reports',
            field=models.BooleanField(default=True, verbose_name='Enable Z-Reports'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_hr_payroll',
            field=models.BooleanField(default=True, verbose_name='Enable HR Payroll'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_hr_roles',
            field=models.BooleanField(default=True, verbose_name='Enable HR Roles'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_hr_shifts',
            field=models.BooleanField(default=True, verbose_name='Enable HR Shifts'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_inventory_ingredients',
            field=models.BooleanField(default=True, verbose_name='Enable Ingredients'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_inventory_predictions',
            field=models.BooleanField(default=True, verbose_name='Enable Stock Predictions'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_inventory_stock',
            field=models.BooleanField(default=True, verbose_name='Enable Stock & Inventory'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_marketing_campaigns',
            field=models.BooleanField(default=True, verbose_name='Enable Campaigns'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_marketing_loyalty',
            field=models.BooleanField(default=True, verbose_name='Enable Loyalty Program'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_menu_items',
            field=models.BooleanField(default=True, verbose_name='Enable Menu Items'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_orders',
            field=models.BooleanField(default=True, verbose_name='Enable Orders History'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_overview',
            field=models.BooleanField(default=True, verbose_name='Enable Overview'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_pos',
            field=models.BooleanField(default=True, verbose_name='Enable POS / New Order'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_settings',
            field=models.BooleanField(default=True, verbose_name='Enable System Settings'),
        ),
    ]
