# Generated by Django 6.0.6 on 2026-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_custom_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='industry',
            field=models.CharField(choices=[('restaurant', 'Restaurant & Cafe'), ('hotel', 'Hotel / Accommodation'), ('retail', 'Retail / Store'), ('beauty', 'Beauty Salon / Spa'), ('service', 'General Service')], default='restaurant', max_length=50, verbose_name='Industry / Sector'),
        ),
    ]
