# Generated by Django 6.0.6 on 2026-07-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='require_login_for_orders',
            field=models.BooleanField(default=False, verbose_name='Require Login for Table Orders'),
        ),
    ]
