# Generated by Django 6.0.6 on 2026-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantsettings_require_login_for_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_online_payment',
            field=models.BooleanField(default=False, verbose_name='Enable Online Payment'),
        ),
    ]
