# Generated by Django 6.0.6 on 2026-07-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_allergies_customer_dietary_preferences_and_more'),
        ('orders', '0004_order_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='customers.customeraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
