# Generated by Django 5.0.3 on 2026-04-29 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('NEW', 'New'), ('REGULAR', 'Regular'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('VIP', 'VIP')], max_length=20, unique=True)),
                ('min_points', models.IntegerField(default=0)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_orders', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_levels', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['min_points', 'min_spend'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required_points', models.IntegerField()),
                ('reward_type', models.CharField(choices=[('DISCOUNT', 'Discount Amount'), ('FREE_PRODUCT', 'Free Product')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('free_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_amount', models.IntegerField(default=1, verbose_name='Points Earned')),
                ('amount_step', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Per Amount Spent')),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rules', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem'), ('BONUS', 'Bonus'), ('EXPIRE', 'Expire')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
