# Generated by Django 6.0.6 on 2026-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_custom_discount_percent_billinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment Amount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Ödendi'), ('PENDING', 'Ödenecek')], default='PENDING', max_length=20, verbose_name='Payment Status'),
        ),
    ]
