# Generated by Django 5.0.3 on 2026-05-04 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('tables', '0004_restauranttable_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer Phone')),
                ('date', models.DateField(verbose_name='Reservation Date')),
                ('time', models.TimeField(verbose_name='Reservation Time')),
                ('guest_count', models.PositiveIntegerField(default=1, verbose_name='Guest Count')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Seated'), ('CANCELLED', 'Cancelled'), ('NOSHOW', 'No Show'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_reservations', to='restaurants.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_reservations', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_reservations', to='tables.restauranttable')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
