# Generated by Django 5.0.3 on 2026-05-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_analytics',
            field=models.BooleanField(default=False, verbose_name='Can View Analytics'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_daily_revenue',
            field=models.BooleanField(default=False, verbose_name='Can View Daily Revenue'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_expenses',
            field=models.BooleanField(default=False, verbose_name='Can View Expenses'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_monthly_revenue',
            field=models.BooleanField(default=False, verbose_name='Can View Monthly Revenue'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_net_profit',
            field=models.BooleanField(default=False, verbose_name='Can View Net Profit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_payroll',
            field=models.BooleanField(default=False, verbose_name='Can View Payroll'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_yearly_revenue',
            field=models.BooleanField(default=False, verbose_name='Can View Yearly Revenue'),
        ),
    ]
