# Generated by Django 5.2.14 on 2026-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_view_analytics_user_can_view_daily_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_campaigns',
            field=models.BooleanField(default=False, verbose_name='Can Manage Campaigns'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_customers',
            field=models.BooleanField(default=False, verbose_name='Can Manage Customers'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, verbose_name='Can Manage Inventory'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_menu',
            field=models.BooleanField(default=False, verbose_name='Can Manage Menu'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_settings',
            field=models.BooleanField(default=False, verbose_name='Can Manage Settings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_ai_reports',
            field=models.BooleanField(default=False, verbose_name='Can View AI Reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_cashier_panel',
            field=models.BooleanField(default=False, verbose_name='Can View Cashier Panel'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_kitchen_screen',
            field=models.BooleanField(default=False, verbose_name='Can View Kitchen Screen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reviews',
            field=models.BooleanField(default=False, verbose_name='Can View Reviews'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_waiter_panel',
            field=models.BooleanField(default=False, verbose_name='Can View Waiter Panel'),
        ),
    ]
