# Generated by Django 5.2.14 on 2026-05-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_can_manage_campaigns_user_can_manage_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_branches',
            field=models.BooleanField(default=False, verbose_name='Can Manage Branches'),
        ),
    ]
