# Generated by Django 6.0.6 on 2026-07-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allergies',
            field=models.JSONField(blank=True, default=list, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list, verbose_name='Dietary Preferences'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Wallet Balance'),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Home, Work', max_length=100, verbose_name='Address Title')),
                ('full_address', models.TextField(verbose_name='Full Address')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('notes', models.TextField(blank=True, verbose_name='Delivery Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
