# Generated by Django 5.0.3 on 2026-05-04 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_tracking_code_orderstagehistory'),
        ('restaurants', '0001_initial'),
        ('tables', '0002_tablereservation_waitercall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='linked_preorder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='orders.order'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='reservation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reservation Date'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='reservation_time_only',
            field=models.TimeField(blank=True, null=True, verbose_name='Reservation Time'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='reservation_time',
            field=models.DateTimeField(verbose_name='Reservation Full Date/Time'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('SEATED', 'Seated'), ('CANCELLED', 'Cancelled'), ('NOSHOW', 'No Show'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
