# Generated by Django 5.0.3 on 2026-05-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_tablereservation_branch_tablereservation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='capacity',
            field=models.PositiveIntegerField(default=2, verbose_name='Capacity'),
        ),
    ]
