# Generated by Django 6.0.6 on 2026-07-19 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoice', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_payrolls', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payroll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoice', to='finance.payrollrecord'),
        ),
    ]
