# Generated by Django 6.0.6 on 2026-07-19 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('taste_rating', models.IntegerField(blank=True, null=True, verbose_name='Taste Rating')),
                ('service_rating', models.IntegerField(blank=True, null=True, verbose_name='Service Rating')),
                ('speed_rating', models.IntegerField(blank=True, null=True, verbose_name='Speed Rating')),
                ('price_rating', models.IntegerField(blank=True, null=True, verbose_name='Price Rating')),
                ('ai_sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative'), ('PENDING', 'Pending AI Analysis')], default='PENDING', max_length=20)),
                ('ai_category', models.CharField(choices=[('TASTE', 'Taste'), ('PRICE', 'Price'), ('DELAY', 'Delay'), ('SERVICE', 'Service'), ('CLEANLINESS', 'Cleanliness'), ('PORTION', 'Portion'), ('PACKAGING', 'Packaging'), ('STAFF', 'Staff'), ('GENERAL', 'General'), ('PENDING', 'Pending AI Analysis')], default='PENDING', max_length=20)),
                ('ai_summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='customers.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
