# Generated by Django 5.0.3 on 2026-04-29 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('preferred_language', models.CharField(blank=True, max_length=10, verbose_name='Preferred Language')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Loyalty Points')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Spent')),
                ('order_count', models.IntegerField(default=0, verbose_name='Order Count')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Order Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-last_order_at', '-created_at'],
                'unique_together': {('restaurant', 'phone', 'email')},
            },
        ),
    ]
