# Generated by Django 6.0.6 on 2026-07-19 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meal_card_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('online_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completed_orders_count', models.PositiveIntegerField(default=0)),
                ('cancelled_orders_count', models.PositiveIntegerField(default=0)),
                ('category_sales', models.JSONField(blank=True, default=dict)),
                ('product_sales', models.JSONField(blank=True, default=dict)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_reports', to='restaurants.restaurant')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-z_number'],
                'unique_together': {('restaurant', 'z_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online'), ('LOYALTY_POINTS', 'Loyalty Points'), ('MEAL_CARD', 'Meal Card')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurants.restaurant')),
                ('z_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.zreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
