# Generated by Django 6.0.6 on 2026-07-19 02:15

import django.db.models.deletion
import tables.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10, verbose_name='Table Number')),
                ('table_name', models.CharField(blank=True, max_length=50, verbose_name='Table Name')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to=tables.models.qr_code_upload_path, verbose_name='QR Code')),
                ('qr_code_url', models.URLField(blank=True, verbose_name='QR Code URL')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Capacity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='restaurants.branch', verbose_name='Branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['table_number'],
                'unique_together': {('restaurant', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer Phone')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email')),
                ('reservation_date', models.DateField(blank=True, null=True, verbose_name='Reservation Date')),
                ('reservation_time_only', models.TimeField(blank=True, null=True, verbose_name='Reservation Time')),
                ('reservation_time', models.DateTimeField(verbose_name='Reservation Full Date/Time')),
                ('number_of_people', models.PositiveIntegerField(default=1, verbose_name='Number of People')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('SEATED', 'Seated'), ('CANCELLED', 'Cancelled'), ('NOSHOW', 'No Show'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('linked_preorder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='tables.restauranttable')),
            ],
            options={
                'ordering': ['-reservation_time'],
            },
        ),
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('waiter', 'Waiter'), ('bill', 'Bill')], default='waiter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('call_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='tables.restauranttable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
