# Generated by Django 6.0.6 on 2026-07-19 02:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20, verbose_name='Salary Type')),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salary Amount')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('salary_period', models.CharField(max_length=100, verbose_name='Salary Period')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Payroll Record',
                'verbose_name_plural': 'Payroll Records',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check-in Time')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hourly Rate')),
                ('calculated_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Calculated Earnings')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Staff Shift',
                'verbose_name_plural': 'Staff Shifts',
                'ordering': ['-check_in'],
            },
        ),
    ]
