# Generated by Django 5.2.13 on 2026-05-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ingredient Name')),
                ('is_removable', models.BooleanField(default=True, verbose_name='Is Removable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_ingredients', to='menu.product')),
            ],
        ),
    ]
