# Generated by Django 5.0.3 on 2026-05-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_productingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
    ]
