# Generated by Django 5.0.3 on 2026-05-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_category_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_diet',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Diet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Discounted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_gluten_free',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Gluten Free'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Popular'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vegan',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Vegan'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vegetarian',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Vegetarian'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spicy_level',
            field=models.IntegerField(blank=True, default=0, verbose_name='Spicy Level (0-5)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20, verbose_name='Stock Status'),
        ),
    ]
