# Generated by Django 5.2.14 on 2026-05-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_modifiergroup_productmodifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
    ]
