# Generated by Django 6.0.6 on 2026-07-19 02:15

import django.db.models.deletion
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_az', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_tr', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_az', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to=menu.models.product_image_upload_path, verbose_name='Image')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Calories')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Protein (g)')),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Carbs (g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fat (g)')),
                ('allergens', models.JSONField(blank=True, default=list, verbose_name='Allergens')),
                ('preparation_time', models.IntegerField(blank=True, null=True, verbose_name='Preparation Time (mins)')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Is Active')),
                ('is_popular', models.BooleanField(blank=True, default=False, verbose_name='Is Popular')),
                ('is_featured', models.BooleanField(blank=True, default=False, verbose_name='Is Featured')),
                ('is_discounted', models.BooleanField(blank=True, default=False, verbose_name='Is Discounted')),
                ('stock_status', models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20, verbose_name='Stock Status')),
                ('spicy_level', models.IntegerField(blank=True, default=0, verbose_name='Spicy Level (0-5)')),
                ('is_vegetarian', models.BooleanField(blank=True, default=False, verbose_name='Is Vegetarian')),
                ('is_vegan', models.BooleanField(blank=True, default=False, verbose_name='Is Vegan')),
                ('is_gluten_free', models.BooleanField(blank=True, default=False, verbose_name='Is Gluten Free')),
                ('is_diet', models.BooleanField(blank=True, default=False, verbose_name='Is Diet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='menu.category', verbose_name='Category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('min_choices', models.IntegerField(default=0, verbose_name='Minimum Choices')),
                ('max_choices', models.IntegerField(default=1, verbose_name='Maximum Choices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='restaurants.restaurant')),
                ('products', models.ManyToManyField(blank=True, related_name='modifier_groups', to='menu.product')),
            ],
            options={
                'verbose_name': 'Modifier Group',
                'verbose_name_plural': 'Modifier Groups',
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ingredient Name')),
                ('is_removable', models.BooleanField(default=True, verbose_name='Is Removable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_ingredients', to='menu.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modifier Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menu.modifiergroup')),
            ],
            options={
                'verbose_name': 'Product Modifier',
                'verbose_name_plural': 'Product Modifiers',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('option_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='single', max_length=20, verbose_name='Option Type')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Option',
                'verbose_name_plural': 'Product Options',
            },
        ),
    ]
