# Generated by Django 5.0.3 on 2026-05-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_prep_time',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated preparation time in minutes', null=True),
        ),
    ]
