# Generated by Django 5.0.3 on 2026-05-04 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_tracking_code_orderstagehistory'),
        ('restaurants', '0001_initial'),
        ('tables', '0004_restauranttable_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_waiter_calls', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_waiter_calls', to='tables.restauranttable')),
            ],
            options={
                'verbose_name': 'Waiter Call',
                'verbose_name_plural': 'Waiter Calls',
                'ordering': ['-created_at'],
            },
        ),
    ]
