# Generated by Django 5.2.13 on 2026-05-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_snapshot_cost_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaiterCall',
        ),
    ]
